name: Arnob's DevBlog
url: http://arnobspeaks.com
description: For rants (and things)
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments
markdown: kramdown
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
defaults:
	-
		scope:
			path: ""
			type: "posts"
		values:
			layout: "post"