name: Arnob's DevBlog
url: http://arnobspeaks.com
description: For rants (and things)
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments
markdown: kramdown
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
gems:
  - jekyll-sitemap